# /utils/constants.py


TILE_SIZE = 64


FPS_LIMIT = 60
SCREEN_TITLE = "Defender"
SCREEN_WIDTH = 15 * TILE_SIZE
SCREEN_HEIGHT = 10 * TILE_SIZE
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

COIN_LIFETIME = 8000
COIN_GOLD_VALUE = 10
COIN_SILVER_VALUE = 5
COIN_BRONZE_VALUE = 1

ENEMY_SOLDIER_HEALTH = 10
ENEMY_SOLDIER_SPEED = 100
ENEMY_ZOMBIE_HEALTH = 5
ENEMY_ZOMBIE_SPEED = 150
ENEMY_KNIGHT_HEALTH = 20
ENEMY_KNIGHT_SPEED = 50
ENEMY_ROBOT_HEALTH = 40
ENEMY_ROBOT_SPEED = 100
ENEMY_TRUCK_HEALTH = 80
ENEMY_TRUCK_SPEED = 100
