# /utils/constants.py


TILE_SIZE = 64


FPS_LIMIT = 60
SCREEN_TITLE = "Defender"
SCREEN_WIDTH = 15 * TILE_SIZE
SCREEN_HEIGHT = 10 * TILE_SIZE
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

COIN_LIFETIME = 8000
COIN_GOLD_VALUE = 10
COIN_SILVER_VALUE = 5
COIN_BRONZE_VALUE = 1
