# /utils/constants.py


TILE_SIZE = 64

HEALTH = 100
SCREEN_TITLE = "Tower Defender"
SCREEN_WIDTH = 15 * TILE_SIZE
SCREEN_HEIGHT = 10 * TILE_SIZE

INFO_UI_MARGIN = 4
INFO_UI_HEIGHT = 24
INFO_UI_WIDTH = 3 * SCREEN_WIDTH // 5
SMALL_INFO_UI_WIDTH = INFO_UI_WIDTH // 3

UI_HEALTHBAR_COLOUR = (79, 189, 101)
WHITE = (255, 255, 255)
BLACK = (21, 19, 21)
UI_BACKGROUND_COLOUR = (*BLACK, 180)

STAT_UI_MARGIN = INFO_UI_MARGIN // 2
STAT_UI_WIDTH = 92
STAT_UI_HEIGHT = 3
STAT_UI_OFFSET_SMALL = 35
STAT_UI_OFFSET_LARGE = STAT_UI_OFFSET_SMALL + STAT_UI_HEIGHT + 10

LAYER_REINFORCEMENT = "Reinforcement"
LAYER_WAYPOINTS = "Waypoints"
LAYER_LOCATIONS = "Locations"
LAYER_PARTICLES = "Particles"
LAYER_ENEMIES = "Enemies"
LAYER_TOWERS = "Towers"
LAYER_SLOTS = "Slots"
LAYER_COINS = "Coins"
